name: Update Dota2 Prices

on:
  schedule:
    - cron: "0 */8 * * *"

  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
      - name: Update prices
        run: npm install && node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'
      - name: Get current date and time
        id: current_datetime
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated Dota2 Prices on ${{ env.CURRENT_DATETIME }}"
